environment: production
address: 0.0.0.0
port: 80
timeout: 30
log: /root/sites_comparison/current/log/thin.log
pid: /root/sites_comparison/shared/current/pids/thin.pid
socket: /root/sites_comparison/current/tmp/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 4
daemonize: true